using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MyPlates.Tx.Carts;
using MyPlates.Tx.Data;

using NUnit.Framework;

namespace MyPlates.Tx.Test.Unit
{
    [TestFixture]
    public class TestShoppingCart
    {
        //private string _traceNum = string.Empty;
        [Test]
        public void ProcessPaymentNormal()
        {
            ShoppingCart sc = new ShoppingCart();
            //NUnit.Framework.Assert.AreEqual(true, sc.ProcessPayment());
        }
        [Test]
        public void ProcessPaymentZero()
        {
            return;
        }
        [Test]
        public void ProcessPaymentNegative()
        {
            return;
        }
        [Test]
        public void ProcessPaymentOverflow()
        {
            return;
        }
        [Test]
        public void ProcessPaymentTwice()
        {
            return;
        }
        [Test]
        public void SendOrderToTxDotNormal()
        {
            LicensePlate plate = new LicensePlate();
            plate.CategoryID = 1;
            plate.TotalCost = 95;
            plate.TxDotYearlyPlateFee = 8;
            plate.TxDotGeneralRevenuePercentage = 30;
            plate.MfgText = "bjorn001";
            plate.OwnerInfo.Street1 = "Street 1";
            plate.OwnerInfo.Street2 = "Street 2";
            plate.OwnerInfo.City = "Round Rock";
            plate.OwnerInfo.State = "Tx";
            plate.OwnerInfo.ZIP = "77777"; 
            plate.OwnerInfo.NameFirst = "Bjorn"; 
            plate.OwnerInfo.NameLast = "Wilmot"; 
            plate.OwnerInfo.Phone = "5555555555";
            plate.OwnerInfo.Email = "bjorn@myplates.com";
            plate.RenewalPeriod = 1;
            //(decimal)MyPlatesData.GetTxDotPaymentAmount(plate.CategoryID, plate.RenewalPeriod);

            //tracenum = JOHN00706232008
            //tracenum is automatically generated by ShoppingCart class

            ShoppingCart sc = new ShoppingCart();
            sc.Plates.Add(plate);
            
            //Assert.AreEqual(true, sc.SendOrderToTxDot("439d169a-9be2-4b3a-8acb-b1009d67ad40"));
        }
    }
}
