//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace TxDot.Web.Services.RtsInvService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RtsInvServiceSoapBinding", Namespace="http://inv.webservices.rts.isd.txdot.com")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RtsAbstractResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RtsAbstractRequest))]
    public partial class RtsInvServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback processDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RtsInvServiceService() {
            this.Url = global::TxDot.Web.Services.Properties.Settings.Default.MyPlates_Tx_TxDot_WebServices_Proxy_RtsInvService_RtsInvServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event processDataCompletedEventHandler processDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://inv.webservices.rts.isd.txdot.com", ResponseNamespace="http://inv.webservices.rts.isd.txdot.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("processDataReturn")]
        public RtsInvResponse[] processData([System.Xml.Serialization.XmlElementAttribute("aarrRequest")] RtsInvRequest[] aarrRequest) {
            object[] results = this.Invoke("processData", new object[] {
                        aarrRequest});
            return ((RtsInvResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void processDataAsync(RtsInvRequest[] aarrRequest) {
            this.processDataAsync(aarrRequest, null);
        }
        
        /// <remarks/>
        public void processDataAsync(RtsInvRequest[] aarrRequest, object userState) {
            if ((this.processDataOperationCompleted == null)) {
                this.processDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessDataOperationCompleted);
            }
            this.InvokeAsync("processData", new object[] {
                        aarrRequest}, this.processDataOperationCompleted, userState);
        }
        
        private void OnprocessDataOperationCompleted(object arg) {
            if ((this.processDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processDataCompleted(this, new processDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.inv.webservices.rts.isd.txdot.com")]
    public partial class RtsInvRequest : RtsAbstractRequest {
        
        private int itmYrField;
        
        private string itmCdField;
        
        private string itmNoField;
        
        private string manufacturingPltNoField;
        
        private string regPltNoField;
        
        private int requestingOfcIssuanceNoField;
        
        private bool fromReserveFlagField;
        
        private bool isaFlgField;
        
        private bool plpFlagField;
        
        /// <remarks/>
        public int itmYr {
            get {
                return this.itmYrField;
            }
            set {
                this.itmYrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string itmCd {
            get {
                return this.itmCdField;
            }
            set {
                this.itmCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string itmNo {
            get {
                return this.itmNoField;
            }
            set {
                this.itmNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string manufacturingPltNo {
            get {
                return this.manufacturingPltNoField;
            }
            set {
                this.manufacturingPltNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string regPltNo {
            get {
                return this.regPltNoField;
            }
            set {
                this.regPltNoField = value;
            }
        }
        
        /// <remarks/>
        public int requestingOfcIssuanceNo {
            get {
                return this.requestingOfcIssuanceNoField;
            }
            set {
                this.requestingOfcIssuanceNoField = value;
            }
        }
        
        /// <remarks/>
        public bool fromReserveFlag {
            get {
                return this.fromReserveFlagField;
            }
            set {
                this.fromReserveFlagField = value;
            }
        }
        
        /// <remarks/>
        public bool isaFlg {
            get {
                return this.isaFlgField;
            }
            set {
                this.isaFlgField = value;
            }
        }
        
        /// <remarks/>
        public bool plpFlag {
            get {
                return this.plpFlagField;
            }
            set {
                this.plpFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RtsInvRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.common.webservices.rts.isd.txdot.com")]
    public abstract partial class RtsAbstractRequest {
        
        private int actionField;
        
        private string callerField;
        
        private string sessionIdField;
        
        private int versionNoField;
        
        /// <remarks/>
        public int action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string caller {
            get {
                return this.callerField;
            }
            set {
                this.callerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        public int versionNo {
            get {
                return this.versionNoField;
            }
            set {
                this.versionNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RtsInvResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.common.webservices.rts.isd.txdot.com")]
    public abstract partial class RtsAbstractResponse {
        
        private string errMsgDescField;
        
        private int errMsgNoField;
        
        private int versionNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errMsgDesc {
            get {
                return this.errMsgDescField;
            }
            set {
                this.errMsgDescField = value;
            }
        }
        
        /// <remarks/>
        public int errMsgNo {
            get {
                return this.errMsgNoField;
            }
            set {
                this.errMsgNoField = value;
            }
        }
        
        /// <remarks/>
        public int versionNo {
            get {
                return this.versionNoField;
            }
            set {
                this.versionNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.inv.webservices.rts.isd.txdot.com")]
    public partial class RtsInvResponse : RtsAbstractResponse {
        
        private string invItmNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string invItmNo {
            get {
                return this.invItmNoField;
            }
            set {
                this.invItmNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void processDataCompletedEventHandler(object sender, processDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RtsInvResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RtsInvResponse[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591