//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace TxDot.Web.Services.RtsAdmService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RtsAdmServiceSoapBinding", Namespace="http://adm.webservices.rts.isd.txdot.com")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RtsAbstractResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RtsAbstractRequest))]
    public partial class RtsAdmServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getCountyInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPltTypesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RtsAdmServiceService() {
            this.Url = global::TxDot.Web.Services.Properties.Settings.Default.MyPlates_Tx_TxDot_WebServices_Proxy_RtsAdmService_RtsAdmServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getCountyInfoCompletedEventHandler getCountyInfoCompleted;
        
        /// <remarks/>
        public event getPltTypesCompletedEventHandler getPltTypesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://adm.webservices.rts.isd.txdot.com", ResponseNamespace="http://adm.webservices.rts.isd.txdot.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getCountyInfoReturn")]
        public RtsOfficeIdResponse[] getCountyInfo([System.Xml.Serialization.XmlElementAttribute("aarrRequest")] RtsDefaultRequest[] aarrRequest) {
            object[] results = this.Invoke("getCountyInfo", new object[] {
                        aarrRequest});
            return ((RtsOfficeIdResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void getCountyInfoAsync(RtsDefaultRequest[] aarrRequest) {
            this.getCountyInfoAsync(aarrRequest, null);
        }
        
        /// <remarks/>
        public void getCountyInfoAsync(RtsDefaultRequest[] aarrRequest, object userState) {
            if ((this.getCountyInfoOperationCompleted == null)) {
                this.getCountyInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCountyInfoOperationCompleted);
            }
            this.InvokeAsync("getCountyInfo", new object[] {
                        aarrRequest}, this.getCountyInfoOperationCompleted, userState);
        }
        
        private void OngetCountyInfoOperationCompleted(object arg) {
            if ((this.getCountyInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCountyInfoCompleted(this, new getCountyInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://adm.webservices.rts.isd.txdot.com", ResponseNamespace="http://adm.webservices.rts.isd.txdot.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getPltTypesReturn")]
        public RtsPlateTypeResponse[] getPltTypes([System.Xml.Serialization.XmlElementAttribute("aarrRequest")] RtsDefaultRequest[] aarrRequest) {
            object[] results = this.Invoke("getPltTypes", new object[] {
                        aarrRequest});
            return ((RtsPlateTypeResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void getPltTypesAsync(RtsDefaultRequest[] aarrRequest) {
            this.getPltTypesAsync(aarrRequest, null);
        }
        
        /// <remarks/>
        public void getPltTypesAsync(RtsDefaultRequest[] aarrRequest, object userState) {
            if ((this.getPltTypesOperationCompleted == null)) {
                this.getPltTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPltTypesOperationCompleted);
            }
            this.InvokeAsync("getPltTypes", new object[] {
                        aarrRequest}, this.getPltTypesOperationCompleted, userState);
        }
        
        private void OngetPltTypesOperationCompleted(object arg) {
            if ((this.getPltTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPltTypesCompleted(this, new getPltTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.common.webservices.rts.isd.txdot.com")]
    public partial class RtsDefaultRequest : RtsAbstractRequest {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RtsDefaultRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.common.webservices.rts.isd.txdot.com")]
    public abstract partial class RtsAbstractRequest {
        
        private int actionField;
        
        private string callerField;
        
        private string sessionIdField;
        
        private int versionNoField;
        
        /// <remarks/>
        public int action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string caller {
            get {
                return this.callerField;
            }
            set {
                this.callerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        public int versionNo {
            get {
                return this.versionNoField;
            }
            set {
                this.versionNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://util.services.rts.isd.txdot.com")]
    public partial class Dollar {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.adm.webservices.rts.isd.txdot.com")]
    public partial class RtsPlateTypeData {
        
        private Dollar addlSetApplFeeField;
        
        private Dollar addlSetRenwlFeeField;
        
        private Dollar firstSetApplFeeField;
        
        private Dollar firstSetRenwlFeeField;
        
        private Dollar pLPFeeField;
        
        private Dollar remakeFeeField;
        
        private Dollar replFeeField;
        
        private int annualPltIndiField;
        
        private int duplsAllowdCdField;
        
        private int mandPltReplAgeField;
        
        private int maxByteCountField;
        
        private int mfgProcsCdField;
        
        private int optPltReplAgeField;
        
        private int pltSetImprtnceCdField;
        
        private int pltSurchargeIndiField;
        
        private int regRenwlCdField;
        
        private int rTSEffDateField;
        
        private int rTSEffEndDateField;
        
        private int spclPrortnIncrmntField;
        
        private int userPltNoIndiField;
        
        private string baseRegPltCdField;
        
        private string dispPltGrpIdField;
        
        private string iSAAllowdCdField;
        
        private string limitedPltGrpIdField;
        
        private string locCntyAuthCdField;
        
        private string locHQAuthCdField;
        
        private string locInetAuthCdField;
        
        private string locRegionAuthCdField;
        
        private string needsProgramCdField;
        
        private string pLPAcctItmCdField;
        
        private string pltOwnrshpCdField;
        
        private string regPltCdField;
        
        private string regPltDesignField;
        
        private string renwlRtrnAddrCdField;
        
        private string shpngAddrCdField;
        
        private string spclPltTypeField;
        
        private string trnsfrCdField;
        
        private string regPltCdDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Dollar addlSetApplFee {
            get {
                return this.addlSetApplFeeField;
            }
            set {
                this.addlSetApplFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Dollar addlSetRenwlFee {
            get {
                return this.addlSetRenwlFeeField;
            }
            set {
                this.addlSetRenwlFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Dollar firstSetApplFee {
            get {
                return this.firstSetApplFeeField;
            }
            set {
                this.firstSetApplFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Dollar firstSetRenwlFee {
            get {
                return this.firstSetRenwlFeeField;
            }
            set {
                this.firstSetRenwlFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Dollar PLPFee {
            get {
                return this.pLPFeeField;
            }
            set {
                this.pLPFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Dollar remakeFee {
            get {
                return this.remakeFeeField;
            }
            set {
                this.remakeFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Dollar replFee {
            get {
                return this.replFeeField;
            }
            set {
                this.replFeeField = value;
            }
        }
        
        /// <remarks/>
        public int annualPltIndi {
            get {
                return this.annualPltIndiField;
            }
            set {
                this.annualPltIndiField = value;
            }
        }
        
        /// <remarks/>
        public int duplsAllowdCd {
            get {
                return this.duplsAllowdCdField;
            }
            set {
                this.duplsAllowdCdField = value;
            }
        }
        
        /// <remarks/>
        public int mandPltReplAge {
            get {
                return this.mandPltReplAgeField;
            }
            set {
                this.mandPltReplAgeField = value;
            }
        }
        
        /// <remarks/>
        public int maxByteCount {
            get {
                return this.maxByteCountField;
            }
            set {
                this.maxByteCountField = value;
            }
        }
        
        /// <remarks/>
        public int mfgProcsCd {
            get {
                return this.mfgProcsCdField;
            }
            set {
                this.mfgProcsCdField = value;
            }
        }
        
        /// <remarks/>
        public int optPltReplAge {
            get {
                return this.optPltReplAgeField;
            }
            set {
                this.optPltReplAgeField = value;
            }
        }
        
        /// <remarks/>
        public int pltSetImprtnceCd {
            get {
                return this.pltSetImprtnceCdField;
            }
            set {
                this.pltSetImprtnceCdField = value;
            }
        }
        
        /// <remarks/>
        public int pltSurchargeIndi {
            get {
                return this.pltSurchargeIndiField;
            }
            set {
                this.pltSurchargeIndiField = value;
            }
        }
        
        /// <remarks/>
        public int regRenwlCd {
            get {
                return this.regRenwlCdField;
            }
            set {
                this.regRenwlCdField = value;
            }
        }
        
        /// <remarks/>
        public int RTSEffDate {
            get {
                return this.rTSEffDateField;
            }
            set {
                this.rTSEffDateField = value;
            }
        }
        
        /// <remarks/>
        public int RTSEffEndDate {
            get {
                return this.rTSEffEndDateField;
            }
            set {
                this.rTSEffEndDateField = value;
            }
        }
        
        /// <remarks/>
        public int spclPrortnIncrmnt {
            get {
                return this.spclPrortnIncrmntField;
            }
            set {
                this.spclPrortnIncrmntField = value;
            }
        }
        
        /// <remarks/>
        public int userPltNoIndi {
            get {
                return this.userPltNoIndiField;
            }
            set {
                this.userPltNoIndiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string baseRegPltCd {
            get {
                return this.baseRegPltCdField;
            }
            set {
                this.baseRegPltCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dispPltGrpId {
            get {
                return this.dispPltGrpIdField;
            }
            set {
                this.dispPltGrpIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ISAAllowdCd {
            get {
                return this.iSAAllowdCdField;
            }
            set {
                this.iSAAllowdCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string limitedPltGrpId {
            get {
                return this.limitedPltGrpIdField;
            }
            set {
                this.limitedPltGrpIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string locCntyAuthCd {
            get {
                return this.locCntyAuthCdField;
            }
            set {
                this.locCntyAuthCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string locHQAuthCd {
            get {
                return this.locHQAuthCdField;
            }
            set {
                this.locHQAuthCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string locInetAuthCd {
            get {
                return this.locInetAuthCdField;
            }
            set {
                this.locInetAuthCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string locRegionAuthCd {
            get {
                return this.locRegionAuthCdField;
            }
            set {
                this.locRegionAuthCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string needsProgramCd {
            get {
                return this.needsProgramCdField;
            }
            set {
                this.needsProgramCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PLPAcctItmCd {
            get {
                return this.pLPAcctItmCdField;
            }
            set {
                this.pLPAcctItmCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pltOwnrshpCd {
            get {
                return this.pltOwnrshpCdField;
            }
            set {
                this.pltOwnrshpCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string regPltCd {
            get {
                return this.regPltCdField;
            }
            set {
                this.regPltCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string regPltDesign {
            get {
                return this.regPltDesignField;
            }
            set {
                this.regPltDesignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string renwlRtrnAddrCd {
            get {
                return this.renwlRtrnAddrCdField;
            }
            set {
                this.renwlRtrnAddrCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string shpngAddrCd {
            get {
                return this.shpngAddrCdField;
            }
            set {
                this.shpngAddrCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spclPltType {
            get {
                return this.spclPltTypeField;
            }
            set {
                this.spclPltTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string trnsfrCd {
            get {
                return this.trnsfrCdField;
            }
            set {
                this.trnsfrCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string regPltCdDesc {
            get {
                return this.regPltCdDescField;
            }
            set {
                this.regPltCdDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.common.webservices.rts.isd.txdot.com")]
    public partial class RtsAddress {
        
        private string cityField;
        
        private string stateField;
        
        private string streetLine1Field;
        
        private string streetLine2Field;
        
        private string zipField;
        
        private string zipP4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string streetLine1 {
            get {
                return this.streetLine1Field;
            }
            set {
                this.streetLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string streetLine2 {
            get {
                return this.streetLine2Field;
            }
            set {
                this.streetLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string zipP4 {
            get {
                return this.zipP4Field;
            }
            set {
                this.zipP4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.adm.webservices.rts.isd.txdot.com")]
    public partial class RtsOfficeIdsData {
        
        private int numberField;
        
        private string countyNameField;
        
        private string emailAddressField;
        
        private string phoneNumberField;
        
        private string tacNameField;
        
        private RtsAddress mailingAddressField;
        
        private RtsAddress physicalAddressField;
        
        /// <remarks/>
        public int number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string countyName {
            get {
                return this.countyNameField;
            }
            set {
                this.countyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tacName {
            get {
                return this.tacNameField;
            }
            set {
                this.tacNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RtsAddress mailingAddress {
            get {
                return this.mailingAddressField;
            }
            set {
                this.mailingAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RtsAddress physicalAddress {
            get {
                return this.physicalAddressField;
            }
            set {
                this.physicalAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RtsPlateTypeResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RtsOfficeIdResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.common.webservices.rts.isd.txdot.com")]
    public abstract partial class RtsAbstractResponse {
        
        private string errMsgDescField;
        
        private int errMsgNoField;
        
        private int versionNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errMsgDesc {
            get {
                return this.errMsgDescField;
            }
            set {
                this.errMsgDescField = value;
            }
        }
        
        /// <remarks/>
        public int errMsgNo {
            get {
                return this.errMsgNoField;
            }
            set {
                this.errMsgNoField = value;
            }
        }
        
        /// <remarks/>
        public int versionNo {
            get {
                return this.versionNoField;
            }
            set {
                this.versionNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.adm.webservices.rts.isd.txdot.com")]
    public partial class RtsPlateTypeResponse : RtsAbstractResponse {
        
        private RtsPlateTypeData[] plateTypeDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plateTypeData", IsNullable=true)]
        public RtsPlateTypeData[] plateTypeData {
            get {
                return this.plateTypeDataField;
            }
            set {
                this.plateTypeDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.adm.webservices.rts.isd.txdot.com")]
    public partial class RtsOfficeIdResponse : RtsAbstractResponse {
        
        private RtsOfficeIdsData[] officeDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("officeData", IsNullable=true)]
        public RtsOfficeIdsData[] officeData {
            get {
                return this.officeDataField;
            }
            set {
                this.officeDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getCountyInfoCompletedEventHandler(object sender, getCountyInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCountyInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCountyInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RtsOfficeIdResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RtsOfficeIdResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getPltTypesCompletedEventHandler(object sender, getPltTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPltTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPltTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RtsPlateTypeResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RtsPlateTypeResponse[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591