//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace TxDot.Web.Services.RtsTransService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RtsTransServiceSoapBinding", Namespace="http://trans.webservices.rts.isd.txdot.com")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RtsAbstractResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RtsAbstractRequest))]
    public partial class RtsTransServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback processDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RtsTransServiceService() {
            this.Url = global::TxDot.Web.Services.Properties.Settings.Default.MyPlates_Tx_TxDot_WebServices_Proxy_RtsTransService_RtsTransServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event processDataCompletedEventHandler processDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trans.webservices.rts.isd.txdot.com", ResponseNamespace="http://trans.webservices.rts.isd.txdot.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("processDataReturn")]
        public RtsTransResponse[] processData([System.Xml.Serialization.XmlElementAttribute("aarrRequest")] RtsTransRequest[] aarrRequest) {
            object[] results = this.Invoke("processData", new object[] {
                        aarrRequest});
            return ((RtsTransResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void processDataAsync(RtsTransRequest[] aarrRequest) {
            this.processDataAsync(aarrRequest, null);
        }
        
        /// <remarks/>
        public void processDataAsync(RtsTransRequest[] aarrRequest, object userState) {
            if ((this.processDataOperationCompleted == null)) {
                this.processDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessDataOperationCompleted);
            }
            this.InvokeAsync("processData", new object[] {
                        aarrRequest}, this.processDataOperationCompleted, userState);
        }
        
        private void OnprocessDataOperationCompleted(object arg) {
            if ((this.processDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processDataCompleted(this, new processDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.trans.webservices.rts.isd.txdot.com")]
    public partial class RtsTransRequest : RtsAbstractRequest {
        
        private int addlSetIndiField;
        
        private System.Nullable<System.DateTime> epayRcveTimeStmpField;
        
        private System.Nullable<System.DateTime> epaySendTimeStmpField;
        
        private System.Nullable<System.DateTime> initReqTimeStmpField;
        
        private int itrntPymntStatusCdField;
        
        private string itrntTraceNoField;
        
        private string mfgPltNoField;
        
        private string orgNoField;
        
        private string pltCdField;
        
        private int pltExpMoField;
        
        private int pltExpYrField;
        
        private string pltNoField;
        
        private RtsAddress pltOwnrAddrField;
        
        private string pltOwnrEmailAddrField;
        
        private string pltOwnrName1Field;
        
        private string pltOwnrName2Field;
        
        private string pltOwnrPhoneField;
        
        private int pltTermField;
        
        private double pymntAmtField;
        
        private string pymntOrderIdField;
        
        private int resComptCntyNoField;
        
        private bool fromReserveField;
        
        private bool isaField;
        
        private bool plpField;
        
        /// <remarks/>
        public int addlSetIndi {
            get {
                return this.addlSetIndiField;
            }
            set {
                this.addlSetIndiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> epayRcveTimeStmp {
            get {
                return this.epayRcveTimeStmpField;
            }
            set {
                this.epayRcveTimeStmpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> epaySendTimeStmp {
            get {
                return this.epaySendTimeStmpField;
            }
            set {
                this.epaySendTimeStmpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> initReqTimeStmp {
            get {
                return this.initReqTimeStmpField;
            }
            set {
                this.initReqTimeStmpField = value;
            }
        }
        
        /// <remarks/>
        public int itrntPymntStatusCd {
            get {
                return this.itrntPymntStatusCdField;
            }
            set {
                this.itrntPymntStatusCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string itrntTraceNo {
            get {
                return this.itrntTraceNoField;
            }
            set {
                this.itrntTraceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mfgPltNo {
            get {
                return this.mfgPltNoField;
            }
            set {
                this.mfgPltNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orgNo {
            get {
                return this.orgNoField;
            }
            set {
                this.orgNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pltCd {
            get {
                return this.pltCdField;
            }
            set {
                this.pltCdField = value;
            }
        }
        
        /// <remarks/>
        public int pltExpMo {
            get {
                return this.pltExpMoField;
            }
            set {
                this.pltExpMoField = value;
            }
        }
        
        /// <remarks/>
        public int pltExpYr {
            get {
                return this.pltExpYrField;
            }
            set {
                this.pltExpYrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pltNo {
            get {
                return this.pltNoField;
            }
            set {
                this.pltNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RtsAddress pltOwnrAddr {
            get {
                return this.pltOwnrAddrField;
            }
            set {
                this.pltOwnrAddrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pltOwnrEmailAddr {
            get {
                return this.pltOwnrEmailAddrField;
            }
            set {
                this.pltOwnrEmailAddrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pltOwnrName1 {
            get {
                return this.pltOwnrName1Field;
            }
            set {
                this.pltOwnrName1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pltOwnrName2 {
            get {
                return this.pltOwnrName2Field;
            }
            set {
                this.pltOwnrName2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pltOwnrPhone {
            get {
                return this.pltOwnrPhoneField;
            }
            set {
                this.pltOwnrPhoneField = value;
            }
        }
        
        /// <remarks/>
        public int pltTerm {
            get {
                return this.pltTermField;
            }
            set {
                this.pltTermField = value;
            }
        }
        
        /// <remarks/>
        public double pymntAmt {
            get {
                return this.pymntAmtField;
            }
            set {
                this.pymntAmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pymntOrderId {
            get {
                return this.pymntOrderIdField;
            }
            set {
                this.pymntOrderIdField = value;
            }
        }
        
        /// <remarks/>
        public int resComptCntyNo {
            get {
                return this.resComptCntyNoField;
            }
            set {
                this.resComptCntyNoField = value;
            }
        }
        
        /// <remarks/>
        public bool fromReserve {
            get {
                return this.fromReserveField;
            }
            set {
                this.fromReserveField = value;
            }
        }
        
        /// <remarks/>
        public bool isa {
            get {
                return this.isaField;
            }
            set {
                this.isaField = value;
            }
        }
        
        /// <remarks/>
        public bool plp {
            get {
                return this.plpField;
            }
            set {
                this.plpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.common.webservices.rts.isd.txdot.com")]
    public partial class RtsAddress {
        
        private string cityField;
        
        private string stateField;
        
        private string streetLine1Field;
        
        private string streetLine2Field;
        
        private string zipField;
        
        private string zipP4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string streetLine1 {
            get {
                return this.streetLine1Field;
            }
            set {
                this.streetLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string streetLine2 {
            get {
                return this.streetLine2Field;
            }
            set {
                this.streetLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string zipP4 {
            get {
                return this.zipP4Field;
            }
            set {
                this.zipP4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RtsTransResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.common.webservices.rts.isd.txdot.com")]
    public abstract partial class RtsAbstractResponse {
        
        private string errMsgDescField;
        
        private int errMsgNoField;
        
        private int versionNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errMsgDesc {
            get {
                return this.errMsgDescField;
            }
            set {
                this.errMsgDescField = value;
            }
        }
        
        /// <remarks/>
        public int errMsgNo {
            get {
                return this.errMsgNoField;
            }
            set {
                this.errMsgNoField = value;
            }
        }
        
        /// <remarks/>
        public int versionNo {
            get {
                return this.versionNoField;
            }
            set {
                this.versionNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.trans.webservices.rts.isd.txdot.com")]
    public partial class RtsTransResponse : RtsAbstractResponse {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RtsTransRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.common.webservices.rts.isd.txdot.com")]
    public abstract partial class RtsAbstractRequest {
        
        private int actionField;
        
        private string callerField;
        
        private string sessionIdField;
        
        private int versionNoField;
        
        /// <remarks/>
        public int action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string caller {
            get {
                return this.callerField;
            }
            set {
                this.callerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        public int versionNo {
            get {
                return this.versionNoField;
            }
            set {
                this.versionNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void processDataCompletedEventHandler(object sender, processDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RtsTransResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RtsTransResponse[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591